apiVersion: tenancy.x-k8s.io/v1alpha1
kind: Tenant
metadata:
  name: tenant-sample
  labels:
    test: foo
spec:
  tenantAdminNamespaceName: tans
  requireNamespacePrefix:   true
  tenantAdmins:
  - kind: Group
    name: foo